SKILL_SEED = [
    ("ma1", "Calculus", "Math", "Calculus fundamentals", "[]"),
    ("ma2", "Linear Algebra", "Math", "Linear Algebra fundamentals", "[]"),
    ("ma3", "Probability", "Math", "Probability fundamentals", "[]"),
    ("ma4", "Statistics", "Math", "Statistics fundamentals", "[]"),
    ("ma5", "Optimization", "Math", "Optimization fundamentals", "[]"),
    ("ma6", "Stochastic Processes", "Math", "Stochastic Processes fundamentals", "[]"),
    ("ma7", "Time Series", "Math", "Time Series fundamentals", "[]"),
    ("cs1", "Python Foundations", "CS", "Python Foundations fundamentals", "[]"),
    ("cs2", "Data Structures", "CS", "Data Structures fundamentals", "[]"),
    ("cs3", "Algorithms", "CS", "Algorithms fundamentals", "[]"),
    ("cs4", "Data Processing", "CS", "Data Processing fundamentals", "[]"),
    ("cs5", "Software Engineering", "CS", "Software Engineering fundamentals", "[]"),
    ("cs6", "Profiling", "CS", "Profiling fundamentals", "[]"),
    ("qu1", "Alpha Research", "Quant", "Alpha Research fundamentals", "[]"),
    ("qu2", "Microstructure Basics", "Quant", "Microstructure Basics fundamentals", "[]"),
    ("qu3", "Portfolio Construction", "Quant", "Portfolio Construction fundamentals", "[]"),
    ("qu4", "Risk Management", "Quant", "Risk Management fundamentals", "[]"),
    ("qu5", "Execution Basics", "Quant", "Execution Basics fundamentals", "[]"),
    ("in1", "Mental Math", "Interview", "Mental Math fundamentals", "[]"),
    ("in2", "Probability Brainteasers", "Interview", "Probability Brainteasers fundamentals", "[]"),
    ("in3", "Coding Rounds", "Interview", "Coding Rounds fundamentals", "[]"),
    ("in4", "Project Explanations", "Interview", "Project Explanations fundamentals", "[]"),
    ("ca1", "Applications", "Career", "Applications fundamentals", "[]"),
    ("ca2", "Networking", "Career", "Networking fundamentals", "[]"),
    ("ca3", "Internships", "Career", "Internships fundamentals", "[]"),
    ("ca4", "Competitions", "Career", "Competitions fundamentals", "[]")
]
